-- V1__init_schema.sql
-- account-hr SERVICE-FIRST veri modeli — PostgreSQL hedefli.
-- Para: NUMERIC(15,2). Tarih: DATE. Zaman damgası: TIMESTAMP.
-- Enum'lar STRING (VARCHAR) olarak saklanır (@Enumerated(EnumType.STRING)).
-- Renk bilgisi DB'de tutulmaz (frontend sabiti).

-- ---------------------------------------------------------------------------
-- Referans / leaf tablolar
-- ---------------------------------------------------------------------------

CREATE TABLE providers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_providers_name UNIQUE (name)
);

CREATE TABLE cards (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank        VARCHAR(255) NOT NULL,
    last_four   VARCHAR(8)   NOT NULL,
    holder_name VARCHAR(255),
    label       VARCHAR(255),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uq_cards_last_four UNIQUE (last_four)
);

CREATE TABLE teams (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_teams_name UNIQUE (name)
);

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL,
    full_name  VARCHAR(255),
    role       VARCHAR(32)  NOT NULL,
    team_id    BIGINT,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_team FOREIGN KEY (team_id) REFERENCES teams (id)
);

CREATE TABLE periods (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- "year"/"month" SQL'de rezerve; prefiksli kolon adları kullanılır.
    period_year  INTEGER      NOT NULL,
    period_month INTEGER      NOT NULL,
    code         VARCHAR(16)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    CONSTRAINT uq_periods_code UNIQUE (code),
    CONSTRAINT uq_periods_year_month UNIQUE (period_year, period_month)
);

-- ---------------------------------------------------------------------------
-- Çekirdek: services + iletişim
-- ---------------------------------------------------------------------------

CREATE TABLE services (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255)  NOT NULL,
    provider_id       BIGINT        NOT NULL,
    default_card_id   BIGINT,
    using_team_id     BIGINT,
    frequency         VARCHAR(32)   NOT NULL,
    active_state      VARCHAR(32)   NOT NULL,
    informational     BOOLEAN       NOT NULL DEFAULT FALSE,
    approx_amount_try NUMERIC(15,2),
    invoice_source    VARCHAR(32),
    purpose           TEXT,
    notes             TEXT,
    created_at        TIMESTAMP     NOT NULL,
    updated_at        TIMESTAMP     NOT NULL,
    CONSTRAINT fk_services_provider     FOREIGN KEY (provider_id)     REFERENCES providers (id),
    CONSTRAINT fk_services_default_card FOREIGN KEY (default_card_id) REFERENCES cards (id),
    CONSTRAINT fk_services_using_team   FOREIGN KEY (using_team_id)   REFERENCES teams (id)
);

CREATE TABLE service_contacts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id      BIGINT       NOT NULL,
    email           VARCHAR(255),
    panel_login_ref VARCHAR(255),
    source          VARCHAR(255),
    is_primary      BOOLEAN      NOT NULL DEFAULT FALSE,
    notes           TEXT,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    CONSTRAINT fk_service_contacts_service FOREIGN KEY (service_id) REFERENCES services (id)
);

-- ---------------------------------------------------------------------------
-- İşlemler: expenses → invoices → files
-- ---------------------------------------------------------------------------

CREATE TABLE expenses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id       BIGINT        NOT NULL,
    period_id        BIGINT        NOT NULL,
    card_id          BIGINT,
    transaction_date DATE          NOT NULL,
    amount           NUMERIC(15,2) NOT NULL,
    currency         VARCHAR(8)    NOT NULL,
    amount_try       NUMERIC(15,2),
    using_team_id    BIGINT,
    informational    BOOLEAN       NOT NULL DEFAULT FALSE,
    purpose          TEXT,
    created_at       TIMESTAMP     NOT NULL,
    updated_at       TIMESTAMP     NOT NULL,
    CONSTRAINT fk_expenses_service   FOREIGN KEY (service_id)    REFERENCES services (id),
    CONSTRAINT fk_expenses_period    FOREIGN KEY (period_id)     REFERENCES periods (id),
    CONSTRAINT fk_expenses_card      FOREIGN KEY (card_id)       REFERENCES cards (id),
    CONSTRAINT fk_expenses_team      FOREIGN KEY (using_team_id) REFERENCES teams (id)
);

CREATE TABLE invoices (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id   BIGINT        NOT NULL,
    provider_id  BIGINT,
    status       VARCHAR(32)   NOT NULL,
    invoice_no   VARCHAR(255),
    invoice_date DATE,
    amount       NUMERIC(15,2),
    currency     VARCHAR(8),
    is_refund    BOOLEAN       NOT NULL DEFAULT FALSE,
    note         TEXT,
    created_at   TIMESTAMP     NOT NULL,
    updated_at   TIMESTAMP     NOT NULL,
    CONSTRAINT fk_invoices_expense  FOREIGN KEY (expense_id)  REFERENCES expenses (id),
    CONSTRAINT fk_invoices_provider FOREIGN KEY (provider_id) REFERENCES providers (id)
);

CREATE TABLE files (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT       NOT NULL,
    file_path   VARCHAR(1024) NOT NULL,
    file_name   VARCHAR(512)  NOT NULL,
    file_type   VARCHAR(32)  NOT NULL,
    mime_type   VARCHAR(255),
    size_bytes  BIGINT,
    uploaded_by BIGINT,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_files_invoice     FOREIGN KEY (invoice_id)  REFERENCES invoices (id),
    CONSTRAINT fk_files_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id)
);

CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(255) NOT NULL,
    entity_id   BIGINT       NOT NULL,
    action      VARCHAR(32)  NOT NULL,
    field_name  VARCHAR(255),
    old_value   TEXT,
    new_value   TEXT,
    changed_by  BIGINT,
    changed_at  TIMESTAMP    NOT NULL,
    note        VARCHAR(1024),
    CONSTRAINT fk_audit_log_changed_by FOREIGN KEY (changed_by) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- Index'ler
-- ---------------------------------------------------------------------------

CREATE INDEX idx_expenses_period_service ON expenses (period_id, service_id);
CREATE INDEX idx_invoices_status         ON invoices (status);
CREATE INDEX idx_invoices_expense        ON invoices (expense_id);

-- Duplicate fatura tespiti: aynı provider + invoice_no tekil (invoice_no dolu olduğunda).
CREATE UNIQUE INDEX uq_invoices_provider_invoice_no
    ON invoices (provider_id, invoice_no)
    WHERE invoice_no IS NOT NULL;
