-- V5__service_credentials.sql
-- E1-05 Servis credential (panel login / API key) saklama — PostgreSQL hedefli.
-- secret kolonu uygulama seviyesinde AES-256-GCM ile ŞİFRELİ saklanır (base64
-- IV||ciphertext||tag). DB'de ASLA düz metin durmaz. username hassas değildir,
-- düz saklanır. Gerçek parolalar E5'te girilir; bu migrasyon altyapıyı kurar.
--
-- NOT: Bu dosya yalnızca PostgreSQL üzerinde (Flyway etkinken) çalışır.
-- Testlerde Flyway kapalıdır; şema entity'lerden Hibernate ile üretilir.

CREATE TABLE service_credentials (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT       NOT NULL,
    cred_type  VARCHAR(32)  NOT NULL,
    username   VARCHAR(255),
    -- AES-256-GCM ciphertext (base64). Düz metin uzunluğu bilinmediği için TEXT.
    secret     TEXT,
    label      VARCHAR(255),
    notes      TEXT,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT fk_service_credentials_service FOREIGN KEY (service_id) REFERENCES services (id)
);

CREATE INDEX idx_service_credentials_service_id ON service_credentials (service_id);
